### ISSUE TITLE
Not seeing the .EXE. Sorry if I'm misunderstanding how to use this!

### ISSUE THREAD

**Issue by SteveHTrann** [nicsant2/SweetCharacterSheet#1]
Hi!

I'm playing DND for the first time and one of the things I'm doing is creating my own character sheet.

I was browsing reddit looking for a character sheet to see if I can find one that looks cool and I came upon yours!  I like the look of it.  However, upon reading your readme, I don't see an .EXE file to execute to run it. I deeply apologize if I'm misunderstanding on how to use your work. Is there any way you can provide assistance on this?

Thank you so much!

**Comment by badZuperman21** [comment]
i have the same problem as steve

**Comment by nsantos19** [comment]
As a warning, this program is no longer being actively maintained. 

The exe can be found in the zip file under the releases page: 


[Release Page](https://github.com/nsantos19/SweetCharacterSheet/releases/tag/v1.1.3
)
